# scripts/lib/per-entry/index-generate.sh — generate + validate the
# impl-plan `_index.md` dependency-derived serial ordering (BD-206 O11).
#
# Public API:
#   per_entry_regenerate_index <stream_key> <stream_dir>
#       Regenerate `<stream_dir>/_index.md` from the `phase-N.md` entry
#       files in the directory. Only the `project-implementation-plan`
#       stream carries `_index.md` (the backlog is unordered → no index,
#       DECISIONS-BD-206-RESTART.md §3 tripwire). Generation derives a
#       topological SEED from each phase file's `Blockers` / `Unblocks` /
#       `Dependencies` SSOT (the deps stay SSOT in the entry files —
#       `_index.md` is NOT a competing source; G-3 (A) derive-seed-then-
#       hand-maintain). Deterministic + idempotent (re-running on the same
#       input yields a byte-identical `_index.md`).
#
#   per_entry_validate_index <stream_key> <stream_dir>
#       The MANDATORY validation script (G-3). Enforces the TWO hard
#       properties against the on-disk `_index.md`:
#         (1) hard-dependency-order consistency — the `_index.md` serial
#             order is a VALID topological order of the rule-based deps
#             (judgment is free ONLY where no hard dep constrains it);
#         (2) per-entry ↔ `_index.md` membership sync — the `_index.md`
#             membership matches the tree's `phase-*.md` files EXACTLY (no
#             missing / extra — analogous to the `_toc.md`-sync Check 33).
#       Prints `[index-validate] PASS …` / `[index-validate] FAIL …` and
#       returns 0 / non-zero. SKIP-lenient (returns 0) when the stream is
#       not impl-plan or the directory is absent.
#
# Realized consumers (architect-doc-reality-reconciliation, rule 8): this
# generator + validator realize the `_index.md` predesign anticipated in
# ARCHITECTURE-BD-185-V2.md §5.3 / -ORDERING-ADDENDUM §A-1 /
# ARCHITECTURE-BD-203-V3-AMENDMENT.md §F.3 (the former `_order` sidecar).
# The realized consumers of this module are:
#   - the impl-plan per-entry stream (`docs/project/implementation-plan/`),
#     whose ordering this module derives + validates;
#   - the support-set admission in `scripts/lib/per-entry/_lib.sh`
#     (`pe_supporting_files_known_for_stream project-implementation-plan`
#     includes `_index.md`, BD-206 MUST-4);
#   - the conformance-enforcement legs that validate the property in BOTH
#     repos: `check_project_index_consistency` in
#     `scripts/validate-pack.py` (pack-side empty-template leg, Check 73)
#     and the `run_conformance` `_index.md` leg in
#     `project-template/scripts/validate-docs.sh` (client-side populated
#     leg). Both implement the same two properties against their own tree.
#
# Architecture:
#   maintenance-docs/v11-implementation/ARCHITECTURE-BD-206.md  O11 (G-3),
#     §8 (rule-8 realization chain)
#   maintenance-docs/v11-implementation/DECISIONS-BD-206-RESTART.md  §3,
#     Item-5, G-3 (the two hard properties)
#   maintenance-docs/v11-implementation/PLAN-BD-206.md  §3 COMMIT C3
#
# Bash 3.2 + macOS BSD utility compatible.
#
# Do NOT add a shebang — this file is sourced, not executed.

if ! type pe_die >/dev/null 2>&1; then
    # shellcheck disable=SC1091
    . "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
fi

# The single stream that carries `_index.md`. The backlog is unordered →
# it has no index (DECISIONS-BD-206-RESTART.md §3 tripwire: impl-plan gets
# `_index.md`; backlog gets none).
PE_INDEX_STREAM="project-implementation-plan"

# ─────────────────────────────────────────────────────────────────
# Shared python helper — emits both the generator and the validator.
# Passed PE_INDEX_MODE = "generate" | "validate". The two share ONE
# dependency-parse + topological-sort grammar so the seed the generator
# emits and the order the validator accepts cannot diverge (single SSOT
# parse of the phase files; ci-check-runtime-compounding: one bounded
# scandir per call, no subprocess-per-entry storm).
# ─────────────────────────────────────────────────────────────────

pe__index_python() {
    PE_INDEX_DIR="$1" \
    PE_INDEX_OUT="$2" \
    PE_INDEX_MODE="$3" \
        python3 - <<'PYEOF'
import os
import re
import sys

stream_dir = os.environ["PE_INDEX_DIR"]
out_path = os.environ.get("PE_INDEX_OUT", "")
mode = os.environ["PE_INDEX_MODE"]  # "generate" | "validate"

ENTRY_RE = re.compile(r"^phase-(\d+)\.md$")
GENERATED_MARKER = (
    "<!-- generated by scripts/lib/per-entry/index-generate.sh "
    "— DO NOT EDIT BY HAND -->"
)
INDEX_HEADER = "# Index — ordering — project-implementation-plan"


def phase_token(num):
    return "phase-%s" % num


def parse_phase_refs(value):
    """Extract every `phase-N` reference from a field value. Tolerates
    `none` / `n/a` / `—` (no refs) and comma / space / `and`-separated
    lists (e.g. `phase-1, phase-2 and phase-3`)."""
    return set(re.findall(r"phase-(\d+)", value))


def field_value(body, field):
    """Return the trimmed value of a `- **Field**:` / `Field:` /
    `**Field**:` labeled line (the form-family bullet shape), or ''."""
    esc = re.escape(field)
    rx = re.compile(
        r"^\s*(?:[-*]\s*)?\*{0,2}" + esc + r"\*{0,2}\s*:(.*)$",
        re.MULTILINE)
    m = rx.search(body)
    return m.group(1).strip().strip("*").strip() if m else ""


def collect_phases(stream_dir):
    """Return (phases, titles, blockers, unblocks) where:
      phases   = sorted list of phase-number strings present on disk;
      titles   = {num: title};
      blockers = {num: set(prereq-nums)}   (this phase comes AFTER these);
      unblocks = {num: set(dependent-nums)} (this phase comes BEFORE these).
    `Blockers` + `Dependencies` + `Prerequisite` all contribute prereq
    edges; `Unblocks` contributes dependent edges. Self-edges + edges to
    non-existent phases are dropped (the validator membership-sync leg
    catches missing files separately)."""
    phases = []
    titles = {}
    blockers = {}
    unblocks = {}
    try:
        names = [e.name for e in os.scandir(stream_dir) if e.is_file()]
    except OSError:
        names = []
    present = set()
    raw = {}
    for name in names:
        m = ENTRY_RE.match(name)
        if not m:
            continue
        num = m.group(1)
        present.add(num)
        try:
            with open(os.path.join(stream_dir, name),
                      encoding="utf-8") as f:
                raw[num] = f.read()
        except OSError:
            raw[num] = ""
    for num in sorted(present, key=int):
        phases.append(num)
        body = raw[num]
        # Title from the `## Phase N — <title>` H2.
        tm = re.search(r"(?m)^## Phase %s — (.+)$" % re.escape(num), body)
        titles[num] = tm.group(1).strip() if tm else "phase-%s" % num
        prereq = set()
        for fld in ("Blockers", "Dependencies", "Prerequisite"):
            prereq |= parse_phase_refs(field_value(body, fld))
        dep = parse_phase_refs(field_value(body, "Unblocks"))
        blockers[num] = prereq
        unblocks[num] = dep
    return phases, titles, blockers, unblocks, present


def build_edges(phases, blockers, unblocks, present):
    """Normalize all dep declarations into a single edge set
    `prereq -> dependent` (prereq MUST appear before dependent in the
    serial order). Drops self-edges + edges referencing absent phases."""
    edges = set()
    for num in phases:
        for b in blockers.get(num, ()):
            if b in present and b != num:
                edges.add((b, num))        # b blocks num → b before num
        for u in unblocks.get(num, ()):
            if u in present and u != num:
                edges.add((num, u))        # num unblocks u → num before u
    return edges


def toposort(phases, edges):
    """Deterministic Kahn topological sort; ties broken by ascending
    phase number. Returns (order, ok): ok=False if a cycle remains
    (cycle members appended in numeric order so output is still total)."""
    indeg = dict((p, 0) for p in phases)
    adj = dict((p, []) for p in phases)
    for (a, b) in edges:
        if a in indeg and b in indeg:
            adj[a].append(b)
            indeg[b] += 1
    ready = sorted((p for p in phases if indeg[p] == 0), key=int)
    order = []
    while ready:
        n = ready.pop(0)
        order.append(n)
        for m in sorted(adj[n], key=int):
            indeg[m] -= 1
            if indeg[m] == 0:
                ready.append(m)
        ready.sort(key=int)
    if len(order) < len(phases):
        # Cycle — append the remaining members in numeric order so the
        # output is total; the validator reports the cycle separately.
        remaining = sorted((p for p in phases if p not in set(order)),
                           key=int)
        order.extend(remaining)
        return order, False
    return order, True


def emit_index(order, titles):
    out = []
    out.append(INDEX_HEADER)
    out.append("")
    out.append(GENERATED_MARKER)
    out.append("")
    out.append("## Serial order")
    out.append("")
    if not order:
        out.append("(empty — no phase entries)")
    else:
        for num in order:
            fn = "phase-%s.md" % num
            out.append("- [phase-%s](./%s) — %s"
                       % (num, fn, titles.get(num, "phase-%s" % num)))
    out.append("")
    while out and out[-1] == "":
        out.pop()
    out.append("")  # single trailing newline
    return "\n".join(out)


def parse_index_order(text):
    """Extract the ordered phase-number list from an `_index.md` body —
    the `- [phase-N](...)` bullets under `## Serial order`, in file
    order. Returns [] if the section / bullets are absent."""
    order = []
    in_section = False
    for line in text.splitlines():
        if line.startswith("## Serial order"):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section:
            m = re.match(r"^- \[phase-(\d+)\]", line)
            if m:
                order.append(m.group(1))
    return order


# ─── GENERATE ────────────────────────────────────────────────────
if mode == "generate":
    phases, titles, blockers, unblocks, present = collect_phases(stream_dir)
    edges = build_edges(phases, blockers, unblocks, present)
    order, _acyclic = toposort(phases, edges)
    content = emit_index(order, titles)
    if out_path:
        with open(out_path, "w", encoding="utf-8", newline="") as f:
            f.write(content)
    else:
        sys.stdout.write(content)
    sys.exit(0)


# ─── VALIDATE ────────────────────────────────────────────────────
if mode == "validate":
    phases, titles, blockers, unblocks, present = collect_phases(stream_dir)
    edges = build_edges(phases, blockers, unblocks, present)

    index_path = os.path.join(stream_dir, "_index.md")
    fails = []

    if not phases:
        # No phase entries — an `_index.md`, if present, must list nothing.
        if os.path.isfile(index_path):
            with open(index_path, encoding="utf-8") as f:
                listed = parse_index_order(f.read())
            if listed:
                fails.append(
                    "_index.md lists phases %s but the tree has no "
                    "phase-*.md entries (membership drift)"
                    % [phase_token(n) for n in sorted(set(listed), key=int)])
        for line in fails:
            sys.stdout.write("MEMBERSHIP %s\n" % line)
        sys.exit(1 if fails else 0)

    if not os.path.isfile(index_path):
        sys.stdout.write(
            "MEMBERSHIP _index.md missing — the impl-plan stream has "
            "%d phase entry/entries but no _index.md ordering\n" % len(phases))
        sys.exit(1)

    with open(index_path, encoding="utf-8") as f:
        index_text = f.read()
    listed = parse_index_order(index_text)

    # (2) membership sync — _index.md set == on-disk phase set, exactly.
    listed_set = set(listed)
    present_set = set(phases)
    missing = sorted(present_set - listed_set, key=int)
    extra = sorted(listed_set - present_set, key=int)
    if missing:
        fails.append("MEMBERSHIP missing from _index.md: %s"
                     % [phase_token(n) for n in missing])
    if extra:
        fails.append("MEMBERSHIP extra in _index.md (no such phase-*.md): %s"
                     % [phase_token(n) for n in extra])
    # Duplicate listing is also a membership defect.
    if len(listed) != len(listed_set):
        seen = set()
        dups = []
        for n in listed:
            if n in seen and n not in dups:
                dups.append(n)
            seen.add(n)
        fails.append("MEMBERSHIP duplicate listing in _index.md: %s"
                     % [phase_token(n) for n in dups])

    # (1) hard-dependency-order consistency — the listed order is a valid
    #     topological order of the rule-based deps. For every edge
    #     prereq -> dependent, position(prereq) < position(dependent) in
    #     the _index.md serial order. Edges among phases NOT both listed
    #     are skipped (the membership leg already flags those).
    pos = dict((n, i) for i, n in enumerate(listed))
    for (a, b) in sorted(edges):
        if a in pos and b in pos and pos[a] >= pos[b]:
            fails.append(
                "ORDER hard-dependency violated: %s must precede %s "
                "(%s blocks/unblocks-into %s) but _index.md lists %s first"
                % (phase_token(a), phase_token(b), phase_token(a),
                   phase_token(b), phase_token(b)))

    # Cycle detection — an impossible-to-satisfy dep set is a hard fail.
    _order, acyclic = toposort(phases, edges)
    if not acyclic:
        fails.append(
            "ORDER dependency cycle detected among the rule-based deps — "
            "no valid topological order exists")

    for line in fails:
        sys.stdout.write("%s\n" % line)
    sys.exit(1 if fails else 0)

# Unknown mode.
sys.stderr.write("pe__index_python: unknown mode %r\n" % mode)
sys.exit(2)
PYEOF
}

# ─────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────

per_entry_regenerate_index() {
    local key="$1"
    local stream_dir="$2"

    [[ -n "$key" ]] || pe_die "per_entry_regenerate_index: stream key required"
    [[ -n "$stream_dir" ]] || \
        pe_die "per_entry_regenerate_index: stream dir required"

    # Only the impl-plan stream carries `_index.md`. Any other stream is a
    # caller error (backlog is unordered → no index).
    if [[ "$key" != "$PE_INDEX_STREAM" ]]; then
        pe_die "per_entry_regenerate_index: only $PE_INDEX_STREAM carries _index.md (got: $key)"
    fi
    [[ -d "$stream_dir" ]] || \
        pe_die "per_entry_regenerate_index: stream dir not found: $stream_dir"

    local index_path="$stream_dir/_index.md"
    local index_tmp
    index_tmp=$(mktemp "$stream_dir/.per-entry-index.XXXXXX") || \
        pe_die "per_entry_regenerate_index: mktemp failed"
    # shellcheck disable=SC2064
    trap "rm -f '$index_tmp'" EXIT

    pe__index_python "$stream_dir" "$index_tmp" generate || \
        pe_die "per_entry_regenerate_index: python generator failed"

    # Idempotency: leave an unchanged on-disk file untouched (no mtime churn).
    if [[ -f "$index_path" ]] && cmp -s "$index_tmp" "$index_path"; then
        rm -f "$index_tmp"
        trap - EXIT
        return 0
    fi

    mv "$index_tmp" "$index_path"
    trap - EXIT
    return 0
}

per_entry_validate_index() {
    local key="$1"
    local stream_dir="$2"

    [[ -n "$key" ]] || pe_die "per_entry_validate_index: stream key required"
    [[ -n "$stream_dir" ]] || \
        pe_die "per_entry_validate_index: stream dir required"

    # SKIP-lenient for non-impl-plan streams + absent directories.
    if [[ "$key" != "$PE_INDEX_STREAM" ]]; then
        return 0
    fi
    if [[ ! -d "$stream_dir" ]]; then
        return 0
    fi

    local out
    if out=$(pe__index_python "$stream_dir" "" validate); then
        echo "[index-validate] PASS — _index.md order is a valid topological order of the rule-based deps + membership matches the tree."
        return 0
    fi
    echo "[index-validate] FAIL — _index.md violates a hard property:" >&2
    printf '%s\n' "$out" | while IFS= read -r line; do
        [[ -n "$line" ]] && echo "  - $line" >&2
    done
    return 1
}
