#!/usr/bin/env bash
# per-entry-regen.sh — regenerate the derived indexes of the per-entry
# documentation streams (`_toc.md`, and `_index.md` for the
# implementation plan).
#
# Each stream under `docs/project/` is a per-entry tree: one file per
# entry, plus derived index files that are GENERATED, never hand-edited.
# Each stream's `_rules.md` states the contract: after any entry edit,
# regenerate the derived indexes before staging. This script is how you
# do that.
#
# Usage:
#   bash scripts/per-entry-regen.sh                 # regenerate every stream
#   bash scripts/per-entry-regen.sh backlog         # one stream (by directory name)
#   bash scripts/per-entry-regen.sh implementation-plan changelog
#   bash scripts/per-entry-regen.sh --check         # report drift, change nothing
#   bash scripts/per-entry-regen.sh --list          # list known streams
#
# Streams (directory name → what is generated):
#   backlog              → _toc.md
#   implementation-plan  → _toc.md + _index.md
#   changelog            → _toc.md
#   groupings            → _toc.md
#
# `--check` exits 1 if any derived index is out of date (useful before
# staging); the default mode rewrites only the files that actually
# changed, so a no-op run leaves mtimes untouched.
#
# `--check` is NOT a mirror of `scripts/validate-docs.sh` — it compares the
# generated bytes, so it is the stricter of the two. On a freshly installed
# project it reports drift on the four `_toc.md` (they ship carrying the
# pack generator's banner) while `validate-docs.sh` is already clean. One
# run without `--check` reconciles them.
#
# A stream directory that does not exist is skipped, not an error.
#
# Exit 0 on success (or clean `--check`); 1 on drift under `--check` or
# on a generation failure.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# This script ships to <project>/scripts/, so the project root is one level up.
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

die() { printf 'per-entry-regen: error: %s\n' "$*" >&2; exit 1; }

# Every stream this script knows, as `<dir-name>` tokens. Kept as a plain
# space-separated string (bash 3.2 has no associative arrays).
KNOWN_STREAMS="backlog implementation-plan changelog groupings"

stream_is_known() {
    local want="$1" s
    for s in $KNOWN_STREAMS; do
        [[ "$s" == "$want" ]] && return 0
    done
    return 1
}

MODE="write"
REQUESTED=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)  MODE="check" ;;
        --list)   printf '%s\n' $KNOWN_STREAMS; exit 0 ;;
        -h|--help)
            sed -n '2,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        -*)       die "unknown option: $1 (try --help)" ;;
        *)
            stream_is_known "$1" || \
                die "unknown stream: $1 (known: $KNOWN_STREAMS)"
            REQUESTED="$REQUESTED $1"
            ;;
    esac
    shift
done

[[ -n "${REQUESTED// /}" ]] || REQUESTED="$KNOWN_STREAMS"

command -v python3 >/dev/null 2>&1 || \
    die "python3 not found on PATH (required to regenerate the derived indexes)"

# ONE python invocation for every requested stream — the parse is bounded by
# the number of entry files, with no subprocess per entry.
PE_ROOT="$PROJECT_ROOT" \
PE_STREAMS="$REQUESTED" \
PE_MODE="$MODE" \
    python3 -  <<'PYEOF'
import os
import re
import sys

root = os.environ["PE_ROOT"]
streams = os.environ["PE_STREAMS"].split()
mode = os.environ["PE_MODE"]

TOC_MARKER = "<!-- generated by scripts/per-entry-regen.sh — DO NOT EDIT BY HAND -->"

# Per-stream: directory under docs/project/, the canonical stream name used
# in the generated headings, the entry-filename pattern, and the TOC axis.
STREAMS = {
    "backlog": {
        "dir": "docs/project/backlog",
        "name": "project-backlog",
        "entry": re.compile(r"^TD-\d+\.md$"),
        "axis": "status",
    },
    "implementation-plan": {
        "dir": "docs/project/implementation-plan",
        "name": "project-implementation-plan",
        "entry": re.compile(r"^phase-\d+\.md$"),
        "axis": "phase",
    },
    "changelog": {
        "dir": "docs/project/changelog",
        "name": "project-changelog",
        "entry": re.compile(r"^\d{4}-\d{2}-\d{2}-[a-z0-9-]+\.md$"),
        "axis": "year-month",
    },
    "groupings": {
        "dir": "docs/project/groupings",
        "name": "project-groupings",
        "entry": re.compile(r"^GRP-(\d{3}|[1-9]\d{3,})\.md$"),
        "axis": "kind",
    },
}

# Status groups render actionable-first, then terminal; unknown statuses
# follow alphabetically. Mirrors the order stated in the backlog _rules.md.
STATUS_ORDER = ["Open", "Unblocked", "Deferred", "Resolved",
                "Deprecated", "Cancelled"]

BACKPOINTER_RE = re.compile(r"^<!-- per-entry source: .*; contract: .* -->$")


def body_lines(text):
    """Entry body with the line-1 back-pointer comment removed."""
    lines = text.splitlines()
    if lines and BACKPOINTER_RE.match(lines[0]):
        lines = lines[1:]
    return lines


def first_match(lines, rx, group=1):
    for ln in lines:
        m = re.match(rx, ln)
        if m:
            return m.group(group).strip()
    return ""


def read_entries(stream_dir, cfg):
    """Return [(filename, entry_id, group_label, title)] plus member counts."""
    entries = []
    counts = {}
    try:
        names = sorted(os.listdir(stream_dir))
    except OSError:
        return entries, counts
    for name in names:
        if name.startswith("_") or not cfg["entry"].match(name):
            continue
        try:
            with open(os.path.join(stream_dir, name),
                      encoding="utf-8", newline="") as f:
                lines = body_lines(f.read())
        except OSError:
            continue
        entry_id = name[:-3]
        axis = cfg["axis"]
        title = ""
        group = ""

        if axis == "status":
            title = first_match(lines, r"^\*\*[A-Z]+-\d+ — (.+?)\*\*")
            group = first_match(lines, r"^Status:\s*(\S+)") or "Open"

        elif axis == "phase":
            title = first_match(lines, r"^## Phase \d+ — (.+)$")
            m = re.match(r"^phase-(\d+)$", entry_id)
            group = "Phase %s" % m.group(1) if m else entry_id

        elif axis == "year-month":
            title = first_match(lines, r"^### \d{4}-\d{2}-\d{2} — (.+)$")
            m = re.match(r"^(\d{4}-\d{2})-", entry_id)
            group = m.group(1) if m else entry_id[:7]

        elif axis == "kind":
            title = first_match(lines, r"^\*\*GRP-\d+ — (.+?)\*\*")
            group = first_match(lines, r"^Kind:\s*(\S+)") or "(no kind)"
            members = first_match(lines, r"^Member-phases:\s*(.*)$", 1)
            counts[entry_id] = len(re.findall(r"phase-\d+", members))

        entries.append((name, entry_id, group, title or entry_id))
    return entries, counts


def order_groups(axis, groups):
    if axis == "status":
        head = [g for g in STATUS_ORDER if g in groups]
        return head + sorted(g for g in groups if g not in STATUS_ORDER)
    if axis == "phase":
        def pkey(g):
            m = re.match(r"^Phase (\d+)$", g)
            return int(m.group(1)) if m else 999
        return sorted(groups, key=pkey)
    if axis == "year-month":
        return sorted(groups, reverse=True)
    return sorted(groups)


def entry_key(axis, item):
    filename, entry_id, title = item
    if axis == "status":
        m = re.match(r"^[A-Z]+-(\d+)$", entry_id)
        return int(m.group(1)) if m else 0
    if axis == "year-month":
        return tuple(-ord(c) for c in filename)
    if axis == "kind":
        m = re.match(r"^GRP-(\d+)$", entry_id)
        return int(m.group(1)) if m else 0
    return entry_id


def render_toc(cfg, entries, counts):
    axis = cfg["axis"]
    grouped = {}
    order = []
    for (filename, entry_id, group, title) in entries:
        if group not in grouped:
            grouped[group] = []
            order.append(group)
        grouped[group].append((filename, entry_id, title))

    out = ["# Table of contents — %s" % cfg["name"], "", TOC_MARKER, ""]
    if not order:
        out.append("(empty — no entries)")
    else:
        for group in order_groups(axis, order):
            out.append("## %s" % group)
            out.append("")
            items = sorted(grouped[group], key=lambda e: entry_key(axis, e))
            for (filename, entry_id, title) in items:
                if axis == "kind":
                    out.append("- %s — %s (phases: %d)"
                               % (entry_id, title, counts.get(entry_id, 0)))
                else:
                    out.append("- [%s](./%s) — %s" % (entry_id, filename, title))
            out.append("")
    while out and out[-1] == "":
        out.pop()
    out.append("")
    return "\n".join(out)


# ── implementation-plan `_index.md`: dependency-derived serial order ──

INDEX_MARKER = ("<!-- generated by scripts/per-entry-regen.sh "
                "— DO NOT EDIT BY HAND -->")
INDEX_HEADER = "# Index — ordering — project-implementation-plan"


def field_value(body, field):
    rx = re.compile(r"^\s*(?:[-*]\s*)?\*{0,2}" + re.escape(field) +
                    r"\*{0,2}\s*:(.*)$", re.MULTILINE)
    m = rx.search(body)
    return m.group(1).strip().strip("*").strip() if m else ""


def phase_refs(value):
    return set(re.findall(r"phase-(\d+)", value))


def collect_phases(stream_dir):
    present, raw = set(), {}
    try:
        names = [e.name for e in os.scandir(stream_dir) if e.is_file()]
    except OSError:
        names = []
    for name in names:
        m = re.match(r"^phase-(\d+)\.md$", name)
        if not m:
            continue
        num = m.group(1)
        present.add(num)
        try:
            with open(os.path.join(stream_dir, name), encoding="utf-8") as f:
                raw[num] = f.read()
        except OSError:
            raw[num] = ""
    phases, titles, blockers, unblocks = [], {}, {}, {}
    for num in sorted(present, key=int):
        phases.append(num)
        body = raw[num]
        tm = re.search(r"(?m)^## Phase %s — (.+)$" % re.escape(num), body)
        titles[num] = tm.group(1).strip() if tm else "phase-%s" % num
        prereq = set()
        for fld in ("Blockers", "Dependencies", "Prerequisite"):
            prereq |= phase_refs(field_value(body, fld))
        blockers[num] = prereq
        unblocks[num] = phase_refs(field_value(body, "Unblocks"))
    return phases, titles, blockers, unblocks, present


def build_edges(phases, blockers, unblocks, present):
    edges = set()
    for num in phases:
        for b in blockers.get(num, ()):
            if b in present and b != num:
                edges.add((b, num))
        for u in unblocks.get(num, ()):
            if u in present and u != num:
                edges.add((num, u))
    return edges


def toposort(phases, edges):
    indeg = dict((p, 0) for p in phases)
    adj = dict((p, []) for p in phases)
    for (a, b) in edges:
        if a in indeg and b in indeg:
            adj[a].append(b)
            indeg[b] += 1
    ready = sorted((p for p in phases if indeg[p] == 0), key=int)
    order = []
    while ready:
        n = ready.pop(0)
        order.append(n)
        for m in sorted(adj[n], key=int):
            indeg[m] -= 1
            if indeg[m] == 0:
                ready.append(m)
        ready.sort(key=int)
    if len(order) < len(phases):
        order.extend(sorted((p for p in phases if p not in set(order)),
                            key=int))
    return order


def render_index(stream_dir):
    phases, titles, blockers, unblocks, present = collect_phases(stream_dir)
    order = toposort(phases, build_edges(phases, blockers, unblocks, present))
    out = [INDEX_HEADER, "", INDEX_MARKER, "", "## Serial order", ""]
    if not order:
        out.append("(empty — no phase entries)")
    else:
        for num in order:
            out.append("- [phase-%s](./phase-%s.md) — %s"
                       % (num, num, titles.get(num, "phase-%s" % num)))
    out.append("")
    while out and out[-1] == "":
        out.pop()
    out.append("")
    return "\n".join(out)


def sync(path, content, mode):
    """Return 'ok' (already current), 'wrote', or 'drift' (--check)."""
    current = None
    if os.path.isfile(path):
        try:
            with open(path, encoding="utf-8", newline="") as f:
                current = f.read()
        except OSError:
            current = None
    if current == content:
        return "ok"
    if mode == "check":
        return "drift"
    # Dot-prefixed temp in the same directory: atomic rename, and a name the
    # stream validators skip if a crash ever leaves one behind.
    head, tail = os.path.split(path)
    tmp = os.path.join(head, ".per-entry-regen.%s.tmp" % tail)
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    os.replace(tmp, path)
    return "wrote"


drifted = 0
touched = 0
for key in streams:
    cfg = STREAMS[key]
    stream_dir = os.path.join(root, cfg["dir"])
    if not os.path.isdir(stream_dir):
        print("  skip: %s/ (not present)" % cfg["dir"])
        continue

    entries, counts = read_entries(stream_dir, cfg)
    toc_path = os.path.join(stream_dir, "_toc.md")
    # An empty stream that has no `_toc.md` yet has nothing to index — leave
    # it alone rather than seeding an index file a fresh install never had.
    # Once a `_toc.md` exists it is kept in sync, empty or not.
    if not entries and not os.path.isfile(toc_path):
        print("  skip: %s/ (no entries yet)" % cfg["dir"])
        continue

    targets = [(toc_path, render_toc(cfg, entries, counts))]
    if key == "implementation-plan":
        # Same rule as `_toc.md`: an empty stream with no `_index.md` yet has
        # no ordering to record.
        index_path = os.path.join(stream_dir, "_index.md")
        if entries or os.path.isfile(index_path):
            targets.append((index_path, render_index(stream_dir)))

    for path, content in targets:
        rel = os.path.relpath(path, root)
        state = sync(path, content, mode)
        if state == "ok":
            print("  ok:    %s (already in sync)" % rel)
        elif state == "wrote":
            print("  wrote: %s" % rel)
            touched += 1
        else:
            print("  DRIFT: %s (out of date — re-run without --check)" % rel)
            drifted += 1

print("")
if mode == "check":
    if drifted:
        print("per-entry-regen: FAIL — %d derived index file(s) out of date."
              % drifted)
        sys.exit(1)
    print("per-entry-regen: OK — every derived index is in sync.")
    sys.exit(0)

print("per-entry-regen: OK — %d file(s) regenerated." % touched)
sys.exit(0)
PYEOF
